-- AlterTable
ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "partial_allowed" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "original_amount" DECIMAL(20,8) NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "locked_amount" DECIMAL(20,8);
